[project]
name = "ranx"
version = "0.0.1"
description = "Add a short description here"
authors = [{ name = "Ameer Arsala", email = "ameer.arsala03@gmail.com" }]
dependencies = [
  "fastapi>=0.112.2,<0.113",
  "typer>=0.12.5,<0.13",
  "httpx>=0.27.2,<0.28",
  "pydantic>2.0",
  "rich>=13.7.1,<13.8",
  "uvicorn[standard]>=0.30.6,<0.31",
  "email-validator>=2.2.0,<3",
]
requires-python = ">= 3.9"

[project.scripts]
ranx = "ranx.cli.main:app"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tool.pixi.pypi-dependencies]
ranx = { path = ".", editable = true }

[tool.pixi.feature.devdeps.dependencies]
pytest = "*"
pre-commit = "*"
black = "*"
hatch = "*"

# [tool.pixi.tasks]
# ranx = "python3 ranx/cli/main.py"

[tool.pixi.feature.devdeps.tasks]
build = "hatch build ./release"

[tool.pixi.environments]
dev = { features = ["devdeps"] }
prod = { features = [] }
