[project]
name = "ranx"
version = "0.1.0"
description = "Add a short description here"
authors = [{ name = "Ameer Arsala", email = "ameer.arsala03@gmail.com" }]
dependencies = [
  "fastapi>=0.112.2,<0.113",
  "typer>=0.12.5,<0.13",
  "httpx>=0.27.2,<0.28",
  "rich>=13.8.0,<14",
  "pydantic>2.0",
]
requires-python = ">= 3.9"

[project.scripts]
ranx = "ranx.cli:app"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
ranx = { path = ".", editable = true }

[tool.pixi.tasks]
ranx = "python3 ranx/cli.py"

[tool.pixi.feature.devdeps.dependencies]
pytest = "*"
pre-commit = "*"
black = "*"
hatch = "*"
jupytext = "*"

[tool.pixi.environments]
dev = { features = ["devdeps"] }
prod = { features = [] }
